x = 6


try:
    print(x)
except ValueError:
    print('This does not work')
    
